// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Pawn.h"
#include "InputActionValue.h"
#include "CosmicSpherePlayer.generated.h"

class UCosmicGravityComponent;
class USphereComponent;
class USceneComponent;
class USkeletalMeshComponent;
class USpringArmComponent;
class UCameraComponent;

// E: Peón principal que utiliza un colisionador esférico para evitar problemas de rotación física.
// I: Main pawn that uses a spherical collider to prevent physical rotation issues.
UCLASS(Blueprintable, BlueprintType)
class COSMICARCHITECTRUNTIME_API ACosmicSpherePlayer : public APawn
{
	GENERATED_BODY()

public:
	// E: Constructor por defecto.
	// I: Default constructor.
	ACosmicSpherePlayer();

	// E: Se utiliza para alinear visualmente al jugador con la gravedad del planeta.
	// I: Used to visually align the player with the planet's gravity.
	virtual void Tick(float DeltaTime) override;

protected:
	virtual void BeginPlay() override;

	// E: Configuración de los vínculos de entrada.
	// I: Setup for input bindings.
	virtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;

	// =========================================================================
	// COMPONENTES DE JERARQUÍA
	// =========================================================================

	// E: Esfera de colisión (Raíz física, no debe rotar).
	// I: Collision sphere (Physical root, must not rotate).
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	USphereComponent* SphereComp;

	// E: Raíz visual (Hijo de la esfera, se rotará por código para mirar al cielo).
	// I: Visual root (Child of sphere, will be rotated by code to face the sky).
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	USceneComponent* VisualRoot;

	// E: Malla del personaje.
	// I: Character mesh.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	USkeletalMeshComponent* PlayerMesh;

	// E: Brazo de la cámara.
	// I: Camera boom.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	USpringArmComponent* SpringArmComp;

	// E: Sensibilidad del ratón.
	// I: Mouse sensitivity.
	UPROPERTY(EditAnywhere, Category = "CosmicArchitect|Input")
	float MouseSensitivity = 1.0f;

	// E: Fuerza que se aplica a la esfera para moverla.
	// I: Force applied to the sphere to move it.
	UPROPERTY(EditAnywhere, Category = "CosmicArchitect|Movement")
	float MovementForce = 1000.0f;

	// E: Cámara principal.
	// I: Main camera.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	UCameraComponent* CameraComp;

	// E: Componente personalizado para detectar la gravedad de los planetas.
	// I: Custom component to detect planet gravity.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Components")
	UCosmicGravityComponent* GravityComp;

	// =========================================================================
	// ENHANCED INPUT SYSTEM
	// =========================================================================

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Input")
	class UInputMappingContext* DefaultMappingContext;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Input")
	class UInputAction* IA_PlayerMove;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Input")
	class UInputAction* IA_PlayerLook;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "CosmicArchitect|Input")
	class UInputAction* IA_PlayerJump;

private:
	// E: Métodos de vinculación de entrada.
	// I: Input binding methods.
	void Move(const FInputActionValue& Value);
	void Look(const FInputActionValue& Value);
	void Jump(const FInputActionValue& Value);

	// E: Variables puras para controlar la rotación de la cámara (Yaw y Pitch).
	// I: Pure variables to control camera rotation (Yaw and Pitch).
	float CameraYaw;
	float CameraPitch;

	// E: Sensibilidad del ratón.
	// I: Mouse sensitivity.
	/*UPROPERTY(EditAnywhere, Category = "CosmicArchitect|Input")
	float MouseSensitivity = 1.0f;*/

	// E: Dirección de movimiento deseada generada por el input de movimiento.
	// I: Desired movement direction generated by movement input.
	FVector TargetFacingDirection;
};