// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GameFramework/Actor.h"
#include "GravityComponent.generated.h"

// E: Enumeración que define los diferentes modos de simulación gravitacional.
// I: Enumeration defining the different gravitational simulation modes.
UENUM(BlueprintType)
enum class ECosmicGravityMode : uint8
{
    // E: Sin efecto de gravedad.
    // I: No gravity effect.
    None           UMETA(DisplayName = "None"),

    // E: Se siente atraído únicamente por el planeta más cercano.
    // I: Attracted only by the nearest planet.
    NearestPlanet  UMETA(DisplayName = "Nearest Planet"),

    // E: Se siente atraído por un actor específico marcado como planeta.
    // I: Attracted by a specific actor marked as a planet.
    SpecificPlanet UMETA(DisplayName = "Specific Planet"),

    // E: Afectado por la gravedad de todos los planetas de la escena.
    // I: Affected by the gravity of all planets in the scene.
    AllPlanets     UMETA(DisplayName = "All Planets"),

    // E: Simulación de N-cuerpos donde todos los objetos se afectan mutuamente.
    // I: N-body simulation where all objects affect each other mutually.
    NBody          UMETA(DisplayName = "N-Body")
};

// E: Componente que maneja físicas gravitacionales personalizadas.
// I: Component handling custom gravitational physics.
UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class COSMICARCHITECTRUNTIME_API UGravityComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UGravityComponent();

    // E: Función de ayuda para obtener la transformación espacial del actor propietario.
    // I: Helper function to get the spatial transform of the owning actor.
    FTransform getTransform() const { return GetOwner()->GetActorTransform(); }

    // E: Modo de gravedad asignado a este componente (siempre visible en el editor).
    // I: Gravity mode assigned to this component (always visible in the editor).
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config")
    ECosmicGravityMode GravityMode = ECosmicGravityMode::NearestPlanet;

    // E: Masa del objeto (visible en el editor SOLO cuando NO es un planeta).
    // I: Object mass (visible in the editor ONLY when it is NOT a planet).
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config",
        meta = (EditCondition = "!IsPlanet", EditConditionHides))
    double Mass = 100.0f;

    // E: Radio físico del planeta en kilómetros (visible SOLO cuando es planeta).
    // I: Physical radius of the planet in kilometers (visible ONLY when it is a planet).
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config",
        meta = (EditCondition = "IsPlanet", EditConditionHides, ClampMin = "0.001",
            UIMin = "0.001", UIMax = "1000000",
            ToolTip = "Radio del planeta en kilómetros"))
    float RadiusKm = 1.0f;

    // E: Aceleración de la gravedad en la superficie (visible SOLO cuando es planeta).
    // I: Gravity acceleration on the surface (visible ONLY when it is a planet).
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config",
        meta = (EditCondition = "IsPlanet", EditConditionHides, ClampMin = "0.0"))
    float SurfaceGravity = 9.8f;

    // E: Determina si este objeto genera un campo gravitatorio que afecta a otros.
    // I: Determines if this object generates a gravitational field that affects others.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config")
    bool AffectsOthers = true;

    // E: Determina si este objeto reacciona a la gravedad generada por otros.
    // I: Determines if this object reacts to the gravity generated by others.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config")
    bool IsAffectedByOthers = true;

    // E: Bandera que indica si este objeto actúa como un cuerpo planetario.
    // I: Flag indicating whether this object acts as a planetary body.
    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Gravity Config")
    bool IsPlanet = false;

    // E: Referencia al actor que ejerce gravedad si el modo es "Planeta Específico".
    // I: Reference to the actor exerting gravity if the mode is "Specific Planet".
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Gravity Config",
        meta = (EditCondition = "GravityMode == ECosmicGravityMode::SpecificPlanet", EditConditionHides))
    AActor* SpecificGravitySource = nullptr;

    // E: Referencia al componente primitivo principal (suele ser la malla para físicas).
    // I: Reference to the root primitive component (usually the mesh for physics).
    UPROPERTY()
    UPrimitiveComponent* RootPrimitive = nullptr;

    // E: Vector que almacena la velocidad actual del objeto.
    // I: Vector storing the current velocity of the object.
    FVector Velocity = FVector::ZeroVector;

    // E: Vector que acumula todas las fuerzas gravitacionales en el frame actual.
    // I: Vector accumulating all gravitational forces in the current frame.
    FVector AccumulatedForce = FVector::ZeroVector;

    // E: Calcula y aplica el movimiento basado en las fuerzas y el tiempo delta.
    // I: Calculates and applies movement based on forces and delta time.
    void Integrate(double DeltaTime);

    // E: Función para actualizar dinámicamente si el objeto es un planeta o no.
    // I: Function to dynamically update whether the object is a planet or not.
    void SetIsPlanet(bool bNewIsPlanet);

protected:
    // E: Se ejecuta cuando el juego comienza o se genera el actor.
    // I: Executed when the game starts or the actor is spawned.
    virtual void BeginPlay() override;

    // E: Se ejecuta cuando el actor es destruido o termina el juego.
    // I: Executed when the actor is destroyed or the game ends.
    virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

    // E: Calcula y devuelve el radio en unidades de Unreal según la escala del objeto.
    // I: Calculates and returns the radius in Unreal units based on the object's scale.
    float GetObjectRadius() const;
};